### ISSUE TITLE
i/o timeout

### ISSUE THREAD

**Issue by snakwu** [networkservicemesh/fanout#14] opened 2020-04-03 09:42 UTC
当我运行一段时间后，去查看日志文，全是i/o timeout
![6efdcae529c794df](https://user-images.githubusercontent.com/5343595/78346987-541a3c00-758f-11ea-8304-d49f66aea0f0.png)
每当打开一个新网页，出现i/o timeout，这时打开网页就卡住！

**Comment by snakwu** [comment] 2020-04-03 09:46
下面是我的配置：
. {
fanout . 127.0.0.1:5301 127.0.0.1:5302 127.0.0.1:5303 {
except 0-100.com 0-6.com 0-gold.net 00.net 00000wg.com 0000go.com 00042.com
}
forward . 127.0.0.1:5304
cache
health
reload 10s
log
}
.:5301 {
bind 127.0.0.1 ::1
forward . tls://8.8.8.8 tls://8.8.4.4 {
tls_servername dns.google
health_check 5s
max_fails 2
expire 90s
}
cache
}
.:5302 {
bind 127.0.0.1 ::1
forward . tls://1.1.1.1 tls://1.0.0.1 {
tls_servername 1dot1dot1dot1.cloudflare-dns.com
health_check 5s
max_fails 2
expire 90s
}
cache
}
.:5303 {
bind 127.0.0.1 ::1
forward . tls://9.9.9.9 tls://149.112.112.112 {
tls_servername dns.quad9.net
health_check 5s
max_fails 2
expire 90s
}
cache
}
.:5304 {
bind 127.0.0.1 ::1
fanout . 202.96.134.33 202.96.128.86 223.5.5.5 119.29.29.29 114.114.114.114
cache
}

**Comment by haiodo** [comment] 2020-04-03 12:03
@denis-tingajkin could you please take a look. Thanks.

**Comment by snakwu** [comment] 2020-04-06 09:16
@denis-tingajkin  这问题有解决办法么？

**Comment by denis-tingajkin** [comment] 2020-04-06 10:05
>这问题有解决办法么？

@snakwu yes, work in progress. You can use the workaround at this moment. Try to add `network TCP` for servers 183.222.53.100 211.137.96.205

**Comment by snakwu** [comment] 2020-04-06 10:09
> > 这问题有解决办法么？
> 
> @snakwu yes, work in progress. You can use the workaround at this moment. Try to add `network TCP` for servers 183.222.53.100 211.137.96.205

但是我这个是运营商的dns，要求是能做到最快速度，如果只用network TCP，tco协议没udp快吧

**Comment by denis-tingajkin** [comment] 2020-04-06 10:23
> 但是我这个是运营商的dns，要求是能做到最快速度，如果只用network TCP，tco协议没udp快吧

Interesting. I thought you try to connect to tcp servers via udp... It looks like servers `183.222.53.100` `211.137.96.205` for some reason can not return NXDOMAIN result via UDP.

**Comment by snakwu** [comment] 2020-04-06 10:46
> > 但是我这个是运营商的dns，要求是能做到最快速度，如果只用network TCP，tco协议没udp快吧
> 
> Interesting. I thought you try to connect to tcp servers via udp... It looks like servers `183.222.53.100` `211.137.96.205` for some reason can not return NXDOMAIN result via UDP for your query.

你可以看我上面的配置，我并不去限制他用tcp或udp去连接运营商的dns，但我可以确定的是这两个dns是支持udp的

**Comment by denis-tingajkin** [comment] 2020-04-06 11:00
forward plugin has some trick for this case. 
It can just switch protocol if something was wrong. 
For example: https://github.com/coredns/coredns/blob/master/plugin/forward/forward.go#L135

**Comment by denis-tingajkin** [comment] 2020-04-06 11:03
@snakwu Can you please check this issue with the option `network TCP`? It can help with main problem detection.

**Comment by snakwu** [comment] 2020-04-06 12:26
> @snakwu Can you please check this issue with the option `network TCP`? It can help with main problem detection.

按正常来说，运营商的dns，肯定是要兼容udp的，有可能tcp反而不兼容的！关于i/o timeout这个错误，我看过一些资料说的是并发连接数过多，前面的没释放后面重连引起的

**Comment by denis-tingajkin** [comment] 2020-04-06 12:32
@snakwu I've tested this config

```
.:53 {
   forward . 183.222.53.100
}
```
And here is result for query `.`:
```
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
2020/04/06 19:31:04 [WARNING] plugin/forward: No healthchecker
```

**Comment by denis-tingajkin** [comment] 2020-04-06 12:34
@snakwu 
Questions:
1. Is `183.222.53.100` public DNS server?
2. How can we check that server works fine?

**Comment by snakwu** [comment] 2020-04-06 12:36
> @snakwu
> Questions:
> 
> 1. Is `183.222.53.100` public DNS server?
> 2. How can we check that server works fine?

是的是中国电信的dns，你试一下这个：202.96.134.33

**Comment by denis-tingajkin** [comment] 2020-04-06 12:36
Also got this error for config above
```
dial udp: address 183.222.53.100: missing port in address
```

**Comment by denis-tingajkin** [comment] 2020-04-06 12:39
@snakwu Do you know what the port uses server 183.222.53.100 for DNS queries?

**Comment by snakwu** [comment] 2020-04-06 12:42
> @snakwu Do you know what the port uses server 183.222.53.100 for DNS queries?

使用的是53，这是运营商样准的dns

**Comment by snakwu** [comment] 2020-04-06 12:43
> @snakwu Do you know what the port uses server 183.222.53.100 for DNS queries?

请使用这个测试：202.96.134.33

**Comment by denis-tingajkin** [comment] 2020-04-06 12:43
@snakwu yep will try to use this IP

**Comment by denis-tingajkin** [comment] 2020-04-06 12:49
@snakwu  I got the next result
```
read udp 192.168.0.11:61654->202.96.134.33:53: i/o timeout
```
Also, I can not `ping  202.96.134.33:53`. Probably this server is not 
available for me.

**Comment by snakwu** [comment] 2020-04-06 12:50
> @snakwu I got the next result
> 
> ```
> read udp 192.168.0.11:61654->202.96.134.33:53: i/o timeout
> ```
> 
> Also, I can not `ping 202.96.134.33:53`. Probably this server is not
> available for me.

可能，因为这是中国电信默认的dns，可能地区不适用

**Comment by denis-tingajkin** [comment] 2020-04-06 12:52
@snakwu Can you check your config and just replace `fanout . 183.222.53.100 211.137.96.205` --> `forward . 183.222.53.100 211.137.96.205`?

**Comment by snakwu** [comment] 2020-04-06 12:53
> @snakwu Can you check your config and just replace `fanout . 183.222.53.100 211.137.96.205` --> `forward . 183.222.53.100 211.137.96.205`?

ok，我现在测试

**Comment by denis-tingajkin** [comment] 2020-04-06 12:54
@snakwu cool, let me know if it is working fine.

**Comment by snakwu** [comment] 2020-04-06 12:56
> @snakwu cool, let me know if it is working fine.

![Screenshot_20200406-205527](https://user-images.githubusercontent.com/5343595/78560685-f9d6e080-7805-11ea-8331-1c091db9391c.jpg)
这是forward的日志

**Comment by denis-tingajkin** [comment] 2020-04-06 13:07
Looking...
Can you also test this change:
```
forward . 183.222.53.100 211.137.96.205 --> fanout . 183.222.53.100 211.137.96.205 {
network TCP
}
```

**Comment by snakwu** [comment] 2020-04-06 13:18
> Looking...
> Can you also test this change?
> 
> ```
> forward . 183.222.53.100 211.137.96.205 --> fanout . 183.222.53.100 211.137.96.205 {
> network TCP
> }
> ```

配置只写这一行？

**Comment by snakwu** [comment] 2020-04-06 13:19
> Looking...
> Can you also test this change?
> 
> ```
> forward . 183.222.53.100 211.137.96.205 --> fanout . 183.222.53.100 211.137.96.205 {
> network TCP
> }
> ```

183.222.53.100 这个不用测试了，我们只要是测试202.96.134.33这个是我运营商默认的dns

**Comment by snakwu** [comment] 2020-04-06 13:35
> Looking...
> Can you also test this change?
> 
> ```
> forward . 183.222.53.100 211.137.96.205 --> fanout . 183.222.53.100 211.137.96.205 {
> network TCP
> }
> ```

[INFO] plugin/reload: Running configuration MD5 = 3789c4e37e95de68b5b304d151936e6a
CoreDNS-1.6.9
linux/amd64, go1.13.4, 4ccd55e9-dirty
[ERROR] plugin/fanout: read udp 127.0.0.1:35696->127.0.0.1:5303: i/o timeout
[ERROR] plugin/fanout: read udp 127.0.0.1:37156->127.0.0.1:5302: i/o timeout
[ERROR] plugin/fanout: read udp 127.0.0.1:44307->127.0.0.1:5303: i/o timeout
[ERROR] plugin/fanout: read udp 127.0.0.1:40266->127.0.0.1:5303: i/o timeout
[ERROR] plugin/fanout: dns: overflow unpacking uint16
[ERROR] plugin/fanout: read udp 192.168.88.100:56937->114.114.114.114:53: i/o timeout
[ERROR] plugin/fanout: read udp 127.0.0.1:60130->127.0.0.1:5303: i/o timeout
[ERROR] plugin/fanout: read udp 127.0.0.1:54570->127.0.0.1:5303: i/o timeout
[ERROR] plugin/fanout: read udp 192.168.88.100:41748->202.96.128.86:53: i/o timeout
[ERROR] plugin/fanout: read udp 192.168.88.100:33474->114.114.114.114:53: i/o timeout
[ERROR] plugin/fanout: read udp 127.0.0.1:59925->127.0.0.1:5303: i/o timeout
[ERROR] plugin/fanout: read udp 127.0.0.1:37276->127.0.0.1:5303: i/o timeout
[ERROR] plugin/fanout: dns: overflow unpacking uint16
[ERROR] plugin/fanout: dns: overflowing header size
[ERROR] plugin/fanout: dns: overflow unpacking uint16
[ERROR] plugin/fanout: read udp 127.0.0.1:58060->127.0.0.1:5303: i/o timeout
[ERROR] plugin/fanout: dns: overflowing header size

**Comment by snakwu** [comment] 2020-04-06 13:36
. {                                                                                    
    fanout . 127.0.0.1:5301 127.0.0.1:5302 127.0.0.1:5303 {                            
        except 0-100.com 0-6.com 0-gold.net 00.net 00000wg.com 0000go.com 00042.com 00$
    }                                                                                  
    forward . 127.0.0.1:5304                                                           
    cache 3600 {                                                                       
        prefetch 10 10m 10%                                                            
    }                                                                                  
    reload 10s                                                                         
}                                                                                      
.:5301 {                                                                               
    forward . tls://8.8.8.8 tls://8.8.4.4 {                                            
        tls_servername dns.google                                                      
        health_check 5s                                                                
        max_fails 2                                                                    
        expire 90s                                                                     
    }                                                                                  
}                                                                                      
.:5302 {                                                                               
    forward . tls://1.1.1.1 tls://1.0.0.1 {                                            
        tls_servername 1dot1dot1dot1.cloudflare-dns.com                                
        health_check 5s                                                                
        max_fails 2                                                                    
        expire 90s                                                                     
    }                                                                                  
}                                                                                      
.:5303 {                                                                               
    forward . tls://9.9.9.9 tls://149.112.112.112 {                                    
        tls_servername dns.quad9.net                                                   
        health_check 5s                                                                
        max_fails 2                                                                    
        expire 90s                                                                     
    }                                                                                  
}                                                                                      
.:5304 {                                                                               
    fanout . 202.96.134.33 202.96.128.86 223.5.5.5 119.29.29.29 114.114.114.114        
}

**Comment by denis-tingajkin** [comment] 2020-04-06 13:39
@snakwu I've reproduced the problem. Sometimes happens i/o timeout because of on query moment server can be busy. 
_Preparing patch..._

**Comment by denis-tingajkin** [comment] 2020-04-06 13:42
@snakwu 

>[ERROR] plugin/fanout: dns: overflow unpacking uint16
>[ERROR] plugin/fanout: dns: overflowing header size
>[ERROR] plugin/fanout: dns: overflow unpacking uint16

It looks like something new :) 
Let's create another issue for TCP case.

**Comment by snakwu** [comment] 2020-04-06 13:44
@denis-tingajkin
这是使用了network TCP

> @snakwu
> 
> > [ERROR] plugin/fanout: dns: overflow unpacking uint16
> > [ERROR] plugin/fanout: dns: overflowing header size
> > [ERROR] plugin/fanout: dns: overflow unpacking uint16
> 
> It looks like something new :)
> Let's create another issue for TCP case.

[INFO] plugin/reload: Running configuration MD5 = 29a5035138c90c6288b3af61b509203b
CoreDNS-1.6.9
linux/amd64, go1.13.4, 4ccd55e9-dirty
[ERROR] plugin/fanout: read tcp 192.168.88.100:52724->223.5.5.5:53: read: connection reset by peer
[ERROR] plugin/fanout: read tcp 192.168.88.100:52734->223.5.5.5:53: read: connection reset by peer
[ERROR] plugin/fanout: read tcp 127.0.0.1:37574->127.0.0.1:5303: i/o timeout
[ERROR] plugin/fanout: read tcp 192.168.88.100:47290->114.114.114.114:53: i/o timeout
[ERROR] plugin/fanout: read tcp 192.168.88.100:53064->223.5.5.5:53: read: connection reset by peer
[ERROR] plugin/fanout: read tcp 127.0.0.1:37856->127.0.0.1:5303: i/o timeout
[ERROR] plugin/fanout: read tcp 127.0.0.1:37926->127.0.0.1:5303: i/o timeout
[ERROR] plugin/fanout: read tcp 127.0.0.1:37954->127.0.0.1:5303: i/o timeout
[ERROR] plugin/fanout: read tcp 127.0.0.1:38020->127.0.0.1:5303: i/o timeout

**Comment by snakwu** [comment] 2020-04-06 13:46
> @snakwu
> 
> > [ERROR] plugin/fanout: dns: overflow unpacking uint16
> > [ERROR] plugin/fanout: dns: overflowing header size
> > [ERROR] plugin/fanout: dns: overflow unpacking uint16
> 
> It looks like something new :)
> Let's create another issue for TCP case.

打开的网页越来越多，io timeout也就越来越多，只要上一出现io timeout 网页就不能打开，要重新刷新

**Comment by snakwu** [comment] 2020-04-06 14:17
> @snakwu
> 
> > [ERROR] plugin/fanout: dns: overflow unpacking uint16
> > [ERROR] plugin/fanout: dns: overflowing header size
> > [ERROR] plugin/fanout: dns: overflow unpacking uint16
> 
> It looks like something new :)
> Let's create another issue for TCP case.

fanout，是我最合适的最需要的插件，希望能修复问题，和改进except的算法使用map算法，那就真的非常酷！！！

**Comment by snakwu** [comment] 2020-04-07 12:34
> @snakwu I've reproduced the problem. Sometimes happens i/o timeout because of on query moment server can be busy. 
> _Preparing patch..._

兄弟，你好，那个PR是不是还有什么问题？我看他一直没合并的？这样没办法测试啊！

**Comment by denis-tingajkin** [comment] 2020-04-07 13:13
@snakwu I think it will be merged today, let's just wait.

**Comment by snakwu** [comment] 2020-04-07 13:36
> @snakwu I think it will be merged today, let's just wait.

ok，thx！！！

**Comment by snakwu** [comment] 2020-04-07 13:42
> @snakwu I think it will be merged today, let's just wait.

我的确是想不明白，为什么迟迟不合并！

**Comment by denis-tingajkin** [comment] 2020-04-07 14:09
@snakwu PR has been merged, could you please check is this Issue solved?

**Comment by snakwu** [comment] 2020-04-07 14:11
> @snakwu PR has been merged, could you please check is this Issue solved?

ok，我马上测试一下

**Comment by snakwu** [comment] 2020-04-07 14:36
> @snakwu PR has been merged, could you please check is this Issue solved?

现在用起来没有timeout错误了，非常感谢，我再观察。
ps：上次提到的except查询方式问题，有消息了吗？

**Comment by denis-tingajkin** [comment] 2020-04-07 14:38
>现在用起来没有timeout错误了，非常感谢，我再观察。

Cool, can we close this issue?

> 上次提到的except查询方式问题，有消息了吗？

I plan to provide PR today for improving `except` directive.

**Comment by snakwu** [comment] 2020-04-07 14:45
> > 现在用起来没有timeout错误了，非常感谢，我再观察。
> 
> Cool, can we close this issue?
> 
> > 上次提到的except查询方式问题，有消息了吗？
> 
> I plan to provide PR today for improving `except` directive.

非常期待，我测试过map算法，的确效果明显快！

**Comment by snakwu** [comment] 2020-04-07 14:45
> > 现在用起来没有timeout错误了，非常感谢，我再观察。
> 
> Cool, can we close this issue?
> 
> > 上次提到的except查询方式问题，有消息了吗？
> 
> I plan to provide PR today for improving `except` directive.

这个issue可以结果了！thx

**Comment by denis-tingajkin** [comment] 2020-04-07 14:47
Fixed by https://github.com/networkservicemesh/fanout/pull/16

**Closed by denis-tingajkin** 2020-04-07 14:47 UTC
Labels: bug
